const mongoose = require('mongoose');

var matchesSchema = new mongoose.Schema({
    game : Number,
    matchId :String,
    length : Number,
    accountID :String,
    participantID : Number,
    championID :String,
    gameResult :String,
    mapSide :String,
    firstBlood :String,
    firstTower :String,
    firstInhib :String,
    kills : Number,
    deaths : Number,
    assists : Number,
    item0 : Number,
    item1 : Number,
    item2 : Number,
    item3 : Number,
    item4 : Number,
    item5 : Number,
    item6 : Number,
    teamTowerKills : Number,
    teamInhibitorKills : Number,
    largestKillingSpree : Number,
    largestMultiKill : Number,
    killingSprees : Number,
    longestTimeSpentLiving : Number,
    doubleKills : Number,
    tripleKills : Number,
    quadraKills : Number,
    pentaKills : Number,
    totalDamageDealt : Number,
    largestCriticalStrike : Number,
    totalDamageDealtToChampions : Number,
    magicDamageDealtToChampions : Number,
    physicalDamageDealtToChampions : Number,
    trueDamageDealtToChampions : Number,
    totalHeal : Number,
    damageSelfMitigated : Number,
    damageDealtToObjectives : Number,
    timeCCingOthers : Number,
    totalDamageTaken : Number,
    magicalDamageTaken : Number,
    physicalDamageTaken : Number,
    trueDamageTaken : Number,
    goldEarned : Number,
    totalMinionsKilled : Number,
    totalTimeCrowdControlDealt : Number,
    championRoleOne :String,
    championRoleTwo :String
});

var matchesModel = mongoose.model('Summoner', matchesSchema);

module.exports = matchesModel;